name: Docker Actions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      
      - name: go
        uses: ./actions/hello-go
        env:
          GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
          ME_TOKEN: ${{secrets.ME_TOKEN}}

      - name: world
        uses: ./ actions/hello-world
        env:
          GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
          ME_TOKEN: ${{secrets.ME_TOKEN}}

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: main_artifact
          path: /all/final.zip
